-- 코드를 작성해주세요
SELECT I.ITEM_ID, I.ITEM_NAME
FROM (
    SELECT ITEM_ID, IFNULL(PARENT_ITEM_ID, 'ROOT') AS PARENT_ITEM_ID
    FROM ITEM_TREE
) T JOIN ITEM_INFO I ON T.ITEM_ID = I.ITEM_ID
WHERE T.PARENT_ITEM_ID = 'ROOT'
ORDER BY I.ITEM_ID