-- 코드를 입력하세요
SELECT I.FOOD_TYPE, I.REST_ID, I.REST_NAME, I.FAVORITES
FROM (
    SELECT FOOD_TYPE, MAX(FAVORITES) AS MAX_FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
) A JOIN REST_INFO I ON A.FOOD_TYPE = I.FOOD_TYPE AND A.MAX_FAVORITES = I.FAVORITES
ORDER BY I.FOOD_TYPE DESC