SELECT B.FOOD_TYPE, B.REST_ID, B.REST_NAME, A.M AS FAVORITES
FROM (
SELECT FOOD_TYPE, MAX(FAVORITES) AS M
FROM REST_INFO
GROUP BY FOOD_TYPE
) A JOIN REST_INFO B ON A.FOOD_TYPE = B.FOOD_TYPE AND A.M = B.FAVORITES
ORDER BY B.FOOD_TYPE DESC