-- 코드를 입력하세요
SELECT II.ANIMAL_ID, II.ANIMAL_TYPE, II.NAME
FROM (
    SELECT *
    FROM ANIMAL_INS I
    WHERE I.SEX_UPON_INTAKE LIKE '%Intact%'
) II JOIN (
    SELECT *
    FROM ANIMAL_OUTS O
    WHERE O.SEX_UPON_OUTCOME LIKE '%Spayed%' or O.SEX_UPON_OUTCOME LIKE '%Neutered%'
) OO ON II.ANIMAL_ID = OO.ANIMAL_ID
