-- 코드를 입력하세요
SELECT U.USER_ID, U.NICKNAME, A.TOTAL_PRICE AS TOTAL_SALES
FROM (
    SELECT WRITER_ID, SUM(PRICE) AS TOTAL_PRICE
    FROM USED_GOODS_BOARD B
    WHERE B.STATUS = 'DONE'
    GROUP BY B.WRITER_ID
) A JOIN USED_GOODS_USER U ON A.WRITER_ID = U.USER_ID
WHERE A.TOTAL_PRICE >= 700000
ORDER BY TOTAL_SALES