-- 코드를 입력하세요
SELECT U.USER_ID, U.NICKNAME, B.TOTAL AS TOTAL_SALES
FROM (
    SELECT WRITER_ID, SUM(PRICE) AS TOTAL
    FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID
) B JOIN USED_GOODS_USER U ON B.WRITER_ID = U.USER_ID
WHERE B.TOTAL >= 700000
ORDER BY TOTAL_SALES