-- 코드를 입력하세요
SELECT DISTINCT(C.CAR_ID)
FROM (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '2022-10-01' AND '2022-10-31'
) H JOIN CAR_RENTAL_COMPANY_CAR C ON H.CAR_ID = C.CAR_ID
WHERE C.CAR_TYPE = '세단'
ORDER BY C.CAR_ID DESC