-- 코드를 작성해주세요
SELECT S.SCORE, S.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM(
SELECT EMP_NO, SUM(SCORE) AS SCORE
FROM HR_GRADE
GROUP BY EMP_NO
ORDER BY SCORE DESC
LIMIT 1) S JOIN HR_EMPLOYEES E ON S.EMP_NO = E.EMP_NO
