SELECT B.CATEGORY, SUM(S.SALES) AS TOTAL_SALES
FROM (
    SELECT *
    FROM BOOK_SALES
    WHERE '2022-01-01' <= SALES_DATE AND '2022-01-31' >= SALES_DATE
) S JOIN BOOK B ON S.BOOK_ID = B.BOOK_ID
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY 