-- 코드를 입력하세요
SELECT B.CATEGORY, SUM(A.SALES) AS TOTAL_SALES
FROM (
    SELECT *
    FROM BOOK_SALES S
    WHERE S.SALES_DATE >= '2022-01-01' AND S.SALES_DATE <= '2022-01-31'
) A JOIN BOOK B ON A.BOOK_ID = B.BOOK_ID
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY
