-- 코드를 입력하세요
SELECT F.CATEGORY, K.MAX_PRICE AS MAX_PRICE, F.PRODUCT_NAME
FROM FOOD_PRODUCT F JOIN (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT 
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
) K ON F.CATEGORY = K.CATEGORY AND F.PRICE = K.MAX_PRICE
ORDER BY K.MAX_PRICE DESC